### ISSUE TITLE
asyncio client doesn't work with Python 3.10

### ISSUE THREAD

**Issue by Velaron** [Mic92/python-mpd2#178]
`File "C:\Users\Velaron\AppData\Local\Programs\Python\Python310\lib\site-packages\mpd\asyncio.py", line 195, in connect
    r, w = await asyncio.open_connection(host, port, loop=loop)
  File "C:\Users\Velaron\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'`

**Comment by mweinelt** [comment]
The loop deprecation was already part of 3.9.7, which we had to roll back due to too much breakages in libraries everywhere. So, yeah, the deprecation policy is weird at best.
