### ISSUE TITLE
ImportError: cannot import name 'MPDClient'

### ISSUE THREAD

**Issue by kasymercieca** [Mic92/python-mpd2#96]
from mpd import MPDClient
ImportError: cannot import name 'MPDClient'

How can i fix the error

**Comment by Mic92** [comment]
Are you sure your are importing from `python-mpd2`? Could it be that you created by accident a file called `mpd.py`?

**Comment by henrikp** [comment]
Similar error over here with Ubuntu 16.04.1 LTS. The import is working with Python 2.7.12 but not with Python 3.5.2

python-mpd2                  1.0.0

`Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpd
>>>
`

`Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'mpd'
`

**Comment by Mic92** [comment]
Closing because there is no indication from my side this is problem with mpd itself.
